#! /bin/sh

set -e

#DEBHELPER#

case "$1" in
        upgrade)
        if dpkg-divert --list mythbuntu-control-centre | grep diverted >/dev/null; then
            dpkg-divert --package mythbuntu-control-centre --remove \
                    --rename --divert /usr/share/mythtv/main_settings.xml.diverted /usr/share/mythtv/main_settings.xml
        fi
        ;;
esac
